### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by cade9522**
#10
Changed readme to provide small description and give installation instruction

### CODE REVIEW

**Review by davidlohle — APPROVED** [review]
Great work as always 😎

**Comment by cade9522** [comment]
Thank you much, you as well man!

**Comment by jessehartloff** [comment]
What issue does this resolve?

**Comment by cade9522** [comment]
@hartloff It was quick modification to the finished prototype; initial merge comment has been edited to reflect the issue.

**Pull request merged**
